create basic auto-compiling katas system
c-lings/clings pull request #1
Opened 2023-11-12 14:10 UTC by Trevodorax

2023-11-13 08:11 UTC, ohmushi requested changes
GG, c'est très clean

2023-11-13 08:11 UTC, ohmushi commented on src/katas/katas.h
> +static const char * kata_file_names[] = {
Je pense qu'il faudrait exporter ce genre d'info dans un fichier de conf, c'est bien pour l'instant mais il faut qu'on garde une trace des todo, ou une roadmap.

2023-11-13 08:11 UTC, ohmushi commented on CMakeLists.txt
> +        src/execution/execution.h
Vaut mieux retirer les .h non ?

2023-11-17 08:21 UTC, Trevodorax commented on src/types/sized_string.c
> +        string.str = NULL;
Non justement l'adresse de la string est dans la struct donc on peut la free comme ça non ?
La seule adresse qui est copiée c'est celle de la struct, mais celle de la .str est la même il me semble

2023-11-17 10:42 UTC, ohmushi commented on src/types/sized_string.c
> +        string.str = NULL;
Le free fonctionne bien puisque l'on passe la bonne adresse, mais la modification de la structure (string.str = NULL) n'a pas d'effet en dehors du scope de la fonction puisque la structure string est une copie.
Si l'on veut que la structure soit modifiée en dehors il faut la référence.

2023-11-17 13:05 UTC, Trevodorax commented on src/types/sized_string.c
> +        string.str = NULL;
oh ok, my bad je change ça

2023-11-17 13:13 UTC, ohmushi approved these changes

2023-11-17 13:13 UTC, merged