Compile and program output in result_buffer
c-lings/clings pull request #9
Opened 2023-11-22 19:47 UTC by TheRealHoko

- still needs buffering fix, not flexible
- add .gitgnore rulesets
- fix realloc typo

2023-11-22 19:54 UTC, Trevodorax requested changes

2023-11-22 19:54 UTC, Trevodorax commented on katas/run_error.c
> +    str = "abc";
you can merge lines 6 and 8

2024-05-06 12:02 UTC, ohmushi commented
Execution system refactored in https://github.com/c-lings/clings/pull/19 for issue https://github.com/c-lings/clings/issues/17

2024-05-06 12:03 UTC, ohmushi commented
Execution system refactored in https://github.com/c-lings/clings/pull/19 for issue https://github.com/c-lings/clings/issues/17

2024-05-06 12:03 UTC, closed without merging